# ===============================
# Database
# ===============================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=hrms
quarkus.datasource.password=hrms
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/hrms

# ===============================
# Hibernate ORM
# ===============================

quarkus.hibernate-orm.database.generation=update